# Use Node.js 20 LTS as the parent image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and pnpm-lock.yaml files
COPY package.json pnpm-lock.yaml ./

# Install pnpm
RUN npm install -g pnpm

# Install dependencies using pnpm
RUN pnpm install --frozen-lockfile

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .

# Build the application using pnpm
RUN pnpm build

# Expose the port the app runs on
EXPOSE 3000

# Run the app using pnpm
CMD ["pnpm", "start"]